[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "chess-transformers"
version = "0.5.0"
description = "Teaching transformers to play chess."
authors = [{ name = "Sagar Vinodababu", email = "sgrvinod@gmail.com" }]
maintainers = [{ name = "Sagar Vinodababu", email = "sgrvinod@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10.0"
dynamic = ["dependencies"]
license = { text = "MIT" }
keywords = ["transformer", "chess", "pytorch", "deep learning", "chess engine"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.urls]
homepage = "https://github.com/sgrvinod/chess-transformers"
source = "https://github.com/sgrvinod/chess-transformers"
changelog = "https://github.com/sgrvinod/chess-transformers/blob/main/CHANGELOG.md"
releasenotes = "https://github.com/sgrvinod/chess-transformers/releases"
issues = "https://github.com/sgrvinod/chess-transformers/issues"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}